###
GET http://localhost:3000/bank-accounts

###
GET http://localhost:3000/bank-accounts/70110626-fb9d-46b9-ab93-d05657dadde0

###
POST http://localhost:3000/bank-accounts
Content-Type: application/json

{
    "account_number": 456
}

###
PATCH  http://localhost:3000/bank-accounts/1
Content-Type: application/json

{
    "account_number": 123
}

###
DELETE http://localhost:3000/bank-accounts/1

###
POST http://localhost:3000/bank-accounts/transfer
Content-Type: application/json

{
    "from": 123,
    "to": 456,
    "amount": 100
}